// Every game of the pond, in the order the home page shows them. A new game is a folder under games/, a page at the root
// and an entry here. store is the id its progress is saved under (see progress.js): two games of one page share it.
// total is how much there is to win, and record(saved, total) the line under the card, empty until there is something to show.
// scripts/check.mjs stops the build when a total no longer matches the game's own data.
import { clean } from '../games/abac-xines/logic.js';
import { clean as concert, noteOf, VALID } from '../games/concert-de-l-estany/logic.js';
import { clean as lab, noteOf as labNote, VALID as LAB_VALID } from '../games/laboratori-de-l-estany/logic.js';
import { clean as pads, noteOf as padNote, VALID as PAD_VALID } from '../games/nenufars-a-trossos/logic.js';
const sum = a => Array.isArray(a) ? a.reduce((x, y) => x + (y | 0), 0) : 0;
// the laboratory works as the concert: the mark of a project comes out of the stars of its levels
const potions = (s, total) => { const p = lab(s), n = Array.from({ length: total }, (_, i) => labNote(p, i)).filter(x => x >= LAB_VALID).length; return n ? `${n} de ${total} projectes` : ''; };
// the fractions game works the same way; a save from before its cursus kept the stars of eight sections, and clean turns them into project marks
const slices = (s, total) => { const p = pads(s), n = Array.from({ length: total }, (_, i) => padNote(p, i)).filter(x => x >= PAD_VALID).length; return n ? `${n} de ${total} projectes` : ''; };
const levels = (n, total) => n ? `${n} de ${total} nivells` : '';
// the division game keeps a mark per project in notes; 80 validates a project. Whatever else notes holds (not a list, junk inside) counts for nothing
const projects = (s, total) => { const n = Array.isArray(s?.notes) ? s.notes.slice(0, total).filter(x => Number.isFinite(x) && x >= 80).length : 0; return n ? `${n} de ${total} projectes` : ''; };
// the abacus game counts projects too, but a profile that has not opened it since the update only holds the old secs: clean makes the project marks from them,
// and from anything else a save of any shape. Unlike the other cards it says 0 de 9 for a save with nothing yet, which is what the plan asks of it
const abacus = (s, total) => `${clean(s).notes.slice(0, total).filter(x => x >= 80).length} de ${total} projectes`;
// the concert keeps the stars of its levels, and the mark of a project comes out of them: clean makes a progress of a save of any shape
const tunes = (s, total) => { const p = concert(s), n = Array.from({ length: total }, (_, i) => noteOf(p, i)).filter(x => x >= VALID).length; return n ? `${n} de ${total} projectes` : ''; };
// the frog game counts levels by section; a save from before that kept stars by world, and a world with a star is a section done
// (worlds 6 and 12 were the mixes, which are no longer sections of their own)
const leaps = s => Array.isArray(s.secs) ? sum(s.secs) : Array.isArray(s.stars) ? s.stars.filter((n, i) => n > 0 && i % 6 < 5).length * 10 : 0;

export const GAMES = [
  { id: 'salts-de-granota', href: 'salts-de-granota.html', store: 'salts-de-granota', tag: 'Càlcul mental', title: 'Salts de Granota',
    what: 'Trucs per sumar i restar de cap, sense comptar amb els dits.', total: 100, record: (s, total) => levels(leaps(s), total),
    icon: `<svg viewBox="-34 -50 68 68" aria-hidden="true"><ellipse cx="0" cy="6" rx="30" ry="10" fill="#2F7F40"/><ellipse cx="0" cy="-12" rx="21" ry="16" fill="#4FB562" stroke="#2F7F40" stroke-width="2"/><circle cx="-10" cy="-27" r="8" fill="#fff" stroke="#2F7F40" stroke-width="2"/><circle cx="10" cy="-27" r="8" fill="#fff" stroke="#2F7F40" stroke-width="2"/><circle cx="-10" cy="-27" r="3.2" fill="#0F3A40"/><circle cx="10" cy="-27" r="3.2" fill="#0F3A40"/><path d="M-8 -8 Q0 -2 8 -8" fill="none" stroke="#2F7F40" stroke-width="2.5" stroke-linecap="round"/></svg>` },
  { id: 'llums', href: 'memoria-visual.html', store: 'memoria-visual', tag: 'Memòria visual', title: 'Repeteix els llums',
    what: "Mira quins llums s'encenen i toca'ls en el mateix ordre.", record: s => s.best > 0 ? `Rècord: ${s.best | 0} punts` : '',
    icon: `<svg viewBox="0 0 68 68" aria-hidden="true"><g fill="#1B3F52"><rect x="4" y="4" width="18" height="18" rx="5"/><rect x="25" y="4" width="18" height="18" rx="5"/><rect x="46" y="4" width="18" height="18" rx="5"/><rect x="4" y="25" width="18" height="18" rx="5"/><rect x="46" y="25" width="18" height="18" rx="5"/><rect x="4" y="46" width="18" height="18" rx="5"/><rect x="25" y="46" width="18" height="18" rx="5"/></g><rect x="25" y="25" width="18" height="18" rx="5" fill="#6FE3FF"/><rect x="46" y="46" width="18" height="18" rx="5" fill="#FF8FD0"/><circle cx="34" cy="34" r="16" fill="none" stroke="#6FE3FF" stroke-width="1.5" opacity="0.6"/></svg>` },
  { id: 'coet', href: 'memoria-visual.html#coet', store: 'memoria-visual', tag: 'Programació', title: 'El coet',
    what: 'Escriu les ordres perquè el coet reculli totes les estrelles.', total: 50, record: (s, total) => levels(sum(s.secs), total),
    icon: `<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M10 14l1.6 3.6 3.9.4-2.9 2.7.8 3.9L10 22.600l-3.400 2 .8-3.9-2.900-2.700 3.900-.4z" fill="#F7C64E"/><g transform="rotate(35 32 32)"><path d="M25 48 Q32 68 39 48Z" fill="#F7C64E"/><path d="M22 38 L11 52 L24 47Z M42 38 L53 52 L40 47Z" fill="#FF6B9A"/><path d="M32 3 C45 14 46 34 42 48 H22 C18 34 19 14 32 3Z" fill="#EAF8F4" stroke="#0A2A3A" stroke-width="2"/><circle cx="32" cy="24" r="6.5" fill="#6FE3FF" stroke="#0A2A3A" stroke-width="2"/></g></svg>` },
  { id: 'abac-xines', href: 'abac-xines.html', store: 'abac-xines', tag: 'Operacions', title: "L'àbac xinès",
    what: 'Mou les boles per sumar, restar, multiplicar i repartir.', total: 9, record: (s, total) => abacus(s, total),
    icon: `<svg viewBox="0 0 64 64" aria-hidden="true"><rect x="5" y="7" width="54" height="50" rx="9" fill="#6B321C" stroke="#F7C64E" stroke-width="1.5"/><rect x="10" y="12" width="44" height="40" rx="4" fill="#061A24"/><path d="M19 12V52M32 12V52M45 12V52" stroke="#F7C64E" stroke-width="1.5"/><rect x="10" y="25" width="44" height="4" fill="#C07A48"/><g fill="#5B4A1C"><ellipse cx="19" cy="15.5" rx="5.5" ry="3"/><ellipse cx="45" cy="15.5" rx="5.5" ry="3"/></g><g fill="#F7C64E"><ellipse cx="32" cy="21.500" rx="5.5" ry="3"/></g><g fill="#7CF5B0"><ellipse cx="45" cy="32.500" rx="5.5" ry="3"/><ellipse cx="45" cy="39" rx="5.5" ry="3"/></g><ellipse cx="32" cy="32.500" rx="5.5" ry="3" fill="#6FE3FF"/><g fill="#B79CFF"><ellipse cx="19" cy="32.500" rx="5.5" ry="3"/><ellipse cx="19" cy="39" rx="5.5" ry="3"/><ellipse cx="19" cy="45.5" rx="5.5" ry="3"/></g><g fill="#1B3F52"><ellipse cx="32" cy="42" rx="5.5" ry="3"/><ellipse cx="32" cy="48.500" rx="5.5" ry="3"/><ellipse cx="45" cy="48.500" rx="5.5" ry="3"/></g></svg>` },
  { id: 'coet-multiplicador', href: 'coet-multiplicador.html', store: 'coet-multiplicador', tag: 'Multiplicar', title: 'El coet multiplicador',
    what: 'Multiplica números grans tros a tros i fes enlairar el coet.', total: 60, record: (s, total) => levels(sum(s.secs), total),
    icon: `<svg viewBox="0 0 64 64" aria-hidden="true"><rect x="4" y="30" width="56" height="30" rx="7" fill="#0A2A3A" stroke="#6FE3FF" stroke-width="1.5"/><path d="M32 30V60M4 45H60" stroke="#6FE3FF" stroke-width="1.5"/><rect x="5" y="46" width="26" height="13" rx="5" fill="#FF8FD0"/><rect x="33" y="31" width="26" height="13" rx="5" fill="#6FE3FF"/><g transform="rotate(35 40 18) translate(22 0) scale(0.56)"><path d="M25 48 Q32 68 39 48Z" fill="#F7C64E"/><path d="M22 38 L11 52 L24 47Z M42 38 L53 52 L40 47Z" fill="#FF6B9A"/><path d="M32 3 C45 14 46 34 42 48 H22 C18 34 19 14 32 3Z" fill="#EAF8F4" stroke="#0A2A3A" stroke-width="2"/><circle cx="32" cy="24" r="6.5" fill="#6FE3FF" stroke="#0A2A3A" stroke-width="2"/></g><path d="M9 10l10 10M19 10L9 20" stroke="#F7C64E" stroke-width="4" stroke-linecap="round"/></svg>` },
  { id: 'nenufars-a-trossos', href: 'nenufars-a-trossos.html', store: 'nenufars-a-trossos', tag: 'Fraccions', title: 'Nenúfars a trossos',
    what: 'Pizzes, xocolata, rellotges i diners: de la primera fracció a sumar-les i fer-ne percentatges.', total: 14, record: (s, total) => slices(s, total),
    icon: `<svg viewBox="-34 -34 68 68" aria-hidden="true"><circle r="30" fill="#1C5A3C"/><path d="M0 0L0 -30A30 30 0 0 1 25.98 15Z M0 0L25.98 15A30 30 0 0 1 0 30Z" fill="#F7C64E"/><circle r="30" fill="none" stroke="#2F7F40" stroke-width="3"/><path d="M0 0V-30M0 0L25.98 -15M0 0L25.98 15M0 0V30M0 0L-25.98 15M0 0L-25.98 -15" stroke="#04131C" stroke-width="2.5" stroke-linecap="round"/></svg>` },
  { id: 'cursus-de-l-estany', href: 'cursus-de-l-estany.html', store: 'cursus-de-l-estany', tag: 'Dividir', title: "El cursus de l'estany",
    what: 'Reparteix, agrupa i divideix a trossos, i caça les errades dels fulls.', total: 8, record: (s, total) => projects(s, total),
    icon: `<svg viewBox="-34 -34 68 68" aria-hidden="true"><circle r="31" fill="none" stroke="#B79CFF" stroke-width="3"/><circle r="21" fill="none" stroke="#6FE3FF" stroke-width="3"/><circle r="11" fill="#1C5A3C" stroke="#7CF5B0" stroke-width="3"/><g fill="#F7C64E"><rect x="-6" y="-1.500" width="12" height="3" rx="1.500"/><circle cy="-5" r="1.800"/><circle cy="5" r="1.800"/></g></svg>` },
  { id: 'concert-de-l-estany', href: 'concert-de-l-estany.html', store: 'concert-de-l-estany', tag: 'Música i mates', title: "El concert de l'estany",
    what: 'Llegeix partitures, talla tubs amb fraccions i omple compassos amb la bateria.', total: 9, record: (s, total) => tunes(s, total),
    icon: `<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M4 60H44" stroke="#2A4B5C" stroke-width="4" stroke-linecap="round"/><rect x="6" y="6" width="8" height="52" rx="3" fill="#FF6B5E"/><rect x="16" y="19" width="8" height="39" rx="3" fill="#F7C64E"/><rect x="26" y="23" width="8" height="35" rx="3" fill="#7CF5B0"/><rect x="36" y="32" width="8" height="26" rx="3" fill="#6FE3FF"/><g fill="none" stroke="#EAF8F4" stroke-width="3" stroke-linecap="round"><path d="M55 30V8q1 7 7 9"/></g><ellipse cx="50" cy="31" rx="6" ry="4.300" transform="rotate(-20 50 31)" fill="#EAF8F4"/></svg>` },
  { id: 'laboratori-de-l-estany', href: 'laboratori-de-l-estany.html', store: 'laboratori-de-l-estany', tag: 'Química i mates', title: "El laboratori de l'estany",
    what: 'Construeix àtoms i molècules, barreja pocions i calcula percentatges.', total: 7, record: (s, total) => potions(s, total),
    icon: `<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M26 6h12v18l16 28q3 8-6 8H16q-9 0-6-8l16-28Z" fill="#0A2A3A" stroke="#EAF8F4" stroke-width="2.5" stroke-linejoin="round"/><path d="M19.500 38h25l8 14q2 5-4 5H15.500q-6 0-4-5Z" fill="#7CF5B0"/><path d="M22 6h20" stroke="#EAF8F4" stroke-width="4" stroke-linecap="round"/><circle cx="27" cy="48" r="3" fill="#EAF8F4" opacity="0.8"/><circle cx="37" cy="44" r="2" fill="#EAF8F4" opacity="0.8"/><circle cx="33" cy="30" r="2.500" fill="#7CF5B0"/><circle cx="50" cy="14" r="5" fill="#FF6B5E"/><circle cx="57" cy="20" r="3.500" fill="#F3FBF8"/><circle cx="44" cy="19" r="3.500" fill="#F3FBF8"/></svg>` }
];
